### ISSUE TITLE
Displaying 'backup+up' backends as 'up'

### ISSUE THREAD

**Issue by haukebruno** [rstruber/dashing-haproxy#1]
The dashboard currently sets backends that are up in general but in backup mode set in HAProxy to 'down'.

**Comment by rstruber** [comment]
Interesting. I wasn't aware of the backup setting for servers. What do you think would be an appropriate display? Should they be skipped? Should they have a different color?

My assumption would be that you don't want to know about them until they are in rotation. But by that time your "down hosts" should be full of big red boxes. Maybe they should just be ignored entirely.

**Comment by rstruber** [comment]
Not sure I entirely understand the issue. In my instance (haproxy 1.6.2) I created a server in backup mode, the status in the csv export is still 'UP', it shouldn't appear in the dashboard at all. So what is it you're asking for?

**Comment by haukebruno** [comment]
sorry for the late answer,

I will check out the 1.6.x versions, we currently run 1.5.x in production. Sorry for bothering mate

**Comment by rstruber** [comment]
No bother. Just haven't heard anything regarding the issue.

Let me know what you find. I'm happy to help find a solution.
